apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mendix-app.fullname" . }}-secret
  labels:
    app: {{ include "mendix-app.name" . }}
    chart: {{ include "mendix-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
stringData:
  admin-password: Kyma4ever!
  db-endpoint: postgresql://v0n9thcbep@5193f84e-3e0b-4a2f-82b0-c3c891c47d79:F8MCL9spdx7UDqpB@5193f84e-3e0b-4a2f-82b0-c3c891c47d79.postgres.database.azure.com:5432/wthxi7n1nh 
  license-key: YOUR_LICENSE_KEY
  license-id: YOUR_LICENSE_ID
