apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mendix-app.fullname" . }}-pvc
  labels:
    app: {{ include "mendix-app.name" . }}
    chart: {{ include "mendix-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

